const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { normalizeName, validatePuzzle, preparePokemon, classify } = require('../core.js');
const data = name => JSON.parse(fs.readFileSync(path.join(__dirname, '../data', name), 'utf8'));
const pokemon = preparePokemon(data('pokemon.json').pokemon);
assert.equal(normalizeName('Flabébé'), 'flabebe');
assert.equal(normalizeName('Mr. Mime'), 'mrmime');
assert.equal(normalizeName('Ho-Oh'), 'hooh');
assert.equal(normalizeName('Nidoran♀'), 'nidoran');
assert.throws(() => validatePuzzle({date:'2026-02-30',center:'a',outer:[...'bcdefg']}));
assert.throws(() => validatePuzzle({date:'2026-10-07',center:'a',outer:[...'abcdef']}));
const sample = preparePokemon([{id:63,name:'Abra'},{id:151,name:'Mew'},{id:250,name:'Ho-Oh'},{id:233,name:'Porygon2'}]);
assert.equal(classify(sample,{date:'2026-10-07',center:'a',outer:[...'bdflor']}).result,'yes');
assert.equal(classify(sample,{date:'2026-10-07',center:'f',outer:[...'abdlor']}).result,'almost');
assert.equal(classify(sample,{date:'2026-10-07',center:'k',outer:[...'lmnpst']}).result,'no');
assert.equal(classify(sample,{date:'2026-10-07',center:'m',outer:[...'ewabcx']}).legal.length,0);
const counts = {yes:0,almost:0,no:0};
const archive = data('history.json');
for (const puzzle of archive.puzzles) counts[classify(pokemon,puzzle).result]++;
assert.deepEqual(counts,archive.stats.counts,'Browser and updater must agree on every archived Bee');
console.log(`Puzzle rules passed. Browser and updater agree across ${archive.puzzles.length} Bees.`);
